<h2>Importing necessary libraries</h2>

In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'absl'

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
data = pd.read_csv('trainX2.csv', header = None)
data.head()

0                       1                    2         3    4   \
0  NaN  city_development_index       training_hours  eduLevel  exp   
1  0.0                    0.92   0.1044776119402985       0.5  1.0   
2  1.0      0.7759999999999999   0.1373134328358209       0.5  0.6   
3  2.0                   0.624  0.24477611940298508       0.5  0.2   
4  3.0                   0.789  0.15223880597014924       0.5  0.0   

                    5         6           7       8              9   \
0           lastNewJob  fromSTEM  enrollType  relExp  gender_Female   
1  0.16666666666666666         1           0       1              0   
2                  1.0         1           0       0              0   
3                  0.0         1           2       0              0   
4                  0.0         0           0       0              0   

            10            11           12  
0  gender_Male  gender_Other  city_labels  
1            1             0            5  
2            1             0           77  
3            1             0           64  
4            1             0           14

In [11]:
data.drop(data.columns[[0]], inplace = True, axis = 1)
data.head()

1                    2         3    4   \
0  city_development_index       training_hours  eduLevel  exp   
1                    0.92   0.1044776119402985       0.5  1.0   
2      0.7759999999999999   0.1373134328358209       0.5  0.6   
3                   0.624  0.24477611940298508       0.5  0.2   
4                   0.789  0.15223880597014924       0.5  0.0   

                    5         6           7       8              9   \
0           lastNewJob  fromSTEM  enrollType  relExp  gender_Female   
1  0.16666666666666666         1           0       1              0   
2                  1.0         1           0       0              0   
3                  0.0         1           2       0              0   
4                  0.0         0           0       0              0   

            10            11           12  
0  gender_Male  gender_Other  city_labels  
1            1             0            5  
2            1             0           77  
3            1             0           64  
4            1             0           14

In [12]:
data = data.iloc[1:]

In [13]:
X = data.to_numpy(dtype='float32')

In [14]:
X.shape

(28762, 12)

In [15]:
output = pd.read_csv('trainY2.csv', header = None)
output.head()

0       1
0  NaN  target
1  0.0     1.0
2  1.0     0.0
3  2.0     0.0
4  3.0     1.0

In [16]:
output.drop(output.columns[[0]], inplace = True, axis = 1)
output.head()

1
0  target
1     1.0
2     0.0
3     0.0
4     1.0

In [17]:
output = output.iloc[1:]

In [18]:
y = output.to_numpy(dtype='float32')

In [19]:
y

array([[1.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

<h3> Splitting the data in test and train data(helps us evaluate the algorithm performance better) </h3>

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

<h3> Trying the decision tree classifier on the data </h3>

In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2150  727]
 [ 676 2200]]
              precision    recall  f1-score   support

         0.0       0.76      0.75      0.75      2877
         1.0       0.75      0.76      0.76      2876

    accuracy                           0.76      5753
   macro avg       0.76      0.76      0.76      5753
weighted avg       0.76      0.76      0.76      5753



<h3> Trying the neural networks on the data </h3>

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(254, input_shape=(11,)),
  tf.keras.layers.Dense(254, activation=tf.nn.relu),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [19]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [20]:
history = model.fit(X_train,y_train, validation_split=0.10, epochs=5)

Epoch 1/5
648/648 [==============================] - 15s 18ms/step - loss: 0.6450 - accuracy: 0.6369 - val_loss: 0.6018 - val_accuracy: 0.7019
Epoch 2/5
648/648 [==============================] - 2s 4ms/step - loss: 0.6061 - accuracy: 0.6949 - val_loss: 0.5991 - val_accuracy: 0.7027
Epoch 3/5
648/648 [==============================] - 2s 3ms/step - loss: 0.5962 - accuracy: 0.6977 - val_loss: 0.5900 - val_accuracy: 0.7032
Epoch 4/5
648/648 [==============================] - 3s 5ms/step - loss: 0.5943 - accuracy: 0.6992 - val_loss: 0.5946 - val_accuracy: 0.7032
Epoch 5/5
648/648 [==============================] - 2s 4ms/step - loss: 0.5928 - accuracy: 0.6969 - val_loss: 0.5894 - val_accuracy: 0.7110


<h3> Trying some more architectures </h3>

In [21]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(70, input_shape=(11,)),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(70, activation=tf.nn.relu),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [22]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [23]:
history = model.fit(X_train,y_train, validation_split=0.1, epochs=30)

Epoch 1/30
648/648 [==============================] - 4s 4ms/step - loss: 0.6529 - accuracy: 0.6214 - val_loss: 0.5989 - val_accuracy: 0.7006
Epoch 2/30
648/648 [==============================] - 4s 6ms/step - loss: 0.6055 - accuracy: 0.6895 - val_loss: 0.5951 - val_accuracy: 0.6997
Epoch 3/30
648/648 [==============================] - 2s 3ms/step - loss: 0.6018 - accuracy: 0.6922 - val_loss: 0.6033 - val_accuracy: 0.7014
Epoch 4/30
648/648 [==============================] - 2s 3ms/step - loss: 0.5975 - accuracy: 0.6972 - val_loss: 0.5960 - val_accuracy: 0.6975
Epoch 5/30
648/648 [==============================] - 3s 5ms/step - loss: 0.5981 - accuracy: 0.6996 - val_loss: 0.5876 - val_accuracy: 0.7071
Epoch 6/30
648/648 [==============================] - 2s 3ms/step - loss: 0.5927 - accuracy: 0.7012 - val_loss: 0.5882 - val_accuracy: 0.7049
Epoch 7/30
648/648 [==============================] - 3s 4ms/step - loss: 0.5916 - accuracy: 0.7004 - val_loss: 0.5836 - val_accuracy: 0.7097
Epoch 

In [24]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(70, input_shape=(11,)),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(90, activation=tf.nn.relu),
  tf.keras.layers.Dense(70, activation=tf.nn.relu),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [25]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [26]:
history = model.fit(X_train,y_train, validation_split=0.1, epochs=30)

Epoch 1/30
648/648 [==============================] - 4s 4ms/step - loss: 0.6425 - accuracy: 0.6385 - val_loss: 0.6041 - val_accuracy: 0.6940
Epoch 2/30
648/648 [==============================] - 3s 5ms/step - loss: 0.6070 - accuracy: 0.6882 - val_loss: 0.5875 - val_accuracy: 0.7080
Epoch 3/30
648/648 [==============================] - 2s 4ms/step - loss: 0.5981 - accuracy: 0.6971 - val_loss: 0.5929 - val_accuracy: 0.7032
Epoch 4/30
648/648 [==============================] - 2s 4ms/step - loss: 0.6034 - accuracy: 0.6936 - val_loss: 0.6009 - val_accuracy: 0.7006
Epoch 5/30
648/648 [==============================] - 3s 4ms/step - loss: 0.5974 - accuracy: 0.6920 - val_loss: 0.5922 - val_accuracy: 0.7023
Epoch 6/30
648/648 [==============================] - 2s 3ms/step - loss: 0.5972 - accuracy: 0.6968 - val_loss: 0.5865 - val_accuracy: 0.7049
Epoch 7/30
648/648 [==============================] - 3s 4ms/step - loss: 0.5904 - accuracy: 0.7020 - val_loss: 0.5877 - val_accuracy: 0.7036
Epoch 

In [27]:
model.evaluate(X_test,y_test,verbose = 1, return_dict = True)

180/180 [==============================] - 0s 2ms/step - loss: 0.5833 - accuracy: 0.7097


{'loss': 0.5832502841949463, 'accuracy': 0.7097166776657104}

In [28]:
model.predict(X_test,verbose = 1)

180/180 [==============================] - 0s 2ms/step


array([[0.7495291 ],
       [0.59306043],
       [0.36576763],
       ...,
       [0.3573401 ],
       [0.32394052],
       [0.14766583]], dtype=float32)

In [29]:
y_pred = model.predict_classes(X_test,verbose = 1)

 51/180 [=======>......................] - ETA: 0s

C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


180/180 [==============================] - 0s 2ms/step


In [30]:
confusion_matrix(y_test, y_pred)

array([[2269,  608],
       [1062, 1814]], dtype=int64)

In [31]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(150, input_shape=(11,)),
  tf.keras.layers.Dense(200, activation=tf.nn.relu),
  tf.keras.layers.Dense(200, activation=tf.nn.relu),
  tf.keras.layers.Dense(200, activation=tf.nn.relu),
  tf.keras.layers.Dense(200, activation=tf.nn.relu),
  tf.keras.layers.Dense(150, activation=tf.nn.relu),
  tf.keras.layers.Dense(70, activation=tf.nn.relu),
  tf.keras.layers.Dense(30, activation=tf.nn.relu),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [32]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [33]:
history = model.fit(X_train,y_train, validation_split=0.1, epochs=30)

Epoch 1/30
648/648 [==============================] - 6s 7ms/step - loss: 0.6530 - accuracy: 0.6248 - val_loss: 0.5984 - val_accuracy: 0.6997
Epoch 2/30
648/648 [==============================] - 4s 6ms/step - loss: 0.6149 - accuracy: 0.6809 - val_loss: 0.5898 - val_accuracy: 0.6984
Epoch 3/30
648/648 [==============================] - 21s 32ms/step - loss: 0.6082 - accuracy: 0.6894 - val_loss: 0.5865 - val_accuracy: 0.7066
Epoch 4/30
648/648 [==============================] - 4s 6ms/step - loss: 0.5993 - accuracy: 0.6946 - val_loss: 0.6005 - val_accuracy: 0.7001
Epoch 5/30
648/648 [==============================] - 5s 7ms/step - loss: 0.5926 - accuracy: 0.7008 - val_loss: 0.5901 - val_accuracy: 0.7066
Epoch 6/30
648/648 [==============================] - 15s 23ms/step - loss: 0.5939 - accuracy: 0.7006 - val_loss: 0.5855 - val_accuracy: 0.7110cu - E
Epoch 7/30
648/648 [==============================] - 14s 22ms/step - loss: 0.5943 - accuracy: 0.7014 - val_loss: 0.5846 - val_accuracy: 0

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.68      0.79      0.73      2877
         1.0       0.75      0.63      0.68      2876

    accuracy                           0.71      5753
   macro avg       0.72      0.71      0.71      5753
weighted avg       0.72      0.71      0.71      5753



In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.68      0.79      0.73      2877
         1.0       0.75      0.63      0.68      2876

    accuracy                           0.71      5753
   macro avg       0.72      0.71      0.71      5753
weighted avg       0.72      0.71      0.71      5753



<h3> We can observe that they don't perform that quite well which is in accordance to the popular belief that neural networks perform much better on unstructured data and not so much on structured ones </h3>

<h3> Tring out one of the popular algorithms used in data science competitions for structured data </h3>
<h3> XGBoost(a variant of decision trees) </h3>

In [19]:
from xgboost import  XGBClassifier
from imblearn.pipeline import Pipeline as imbPipe
from sklearn.model_selection import GridSearchCV

In [20]:
import warnings
warnings.filterwarnings("ignore")
XGBoost_pipe = imbPipe([
    ("XGBoost", XGBClassifier(random_state=42,n_jobs=-1,tree_method="hist"))
])

In [21]:
params={
    "XGBoost__max_depth": [20,21],
    "XGBoost__min_child_weight":[22,23],
    "XGBoost__n_estimators":[25,27],
    "XGBoost__subsample":[0.4,0.5,0.6],
    "XGBoost__colsample_bytree":[0.4,0.5,0.6],
    "XGBoost__gamma":[1,2,3],
    
}

XGBoost_grid = GridSearchCV(XGBoost_pipe, params, n_jobs=-1,cv=3,scoring="roc_auc")
XGBoost_grid.fit(X_train, y_train)
print("Best Parameters for Model:  ",XGBoost_grid.best_params_)
y_pred=XGBoost_grid.predict(X_train)
print("\n")
print(classification_report(y_train, y_pred))

[20:11:58] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Best Parameters for Model:   {'XGBoost__colsample_bytree': 0.5, 'XGBoost__gamma': 3, 'XGBoost__max_depth': 20, 'XGBoost__min_child_weight': 22, 'XGBoost__n_estimators': 27, 'XGBoost__subsample': 0.6}


              precision    recall  f1-score   support

         0.0       0.80      0.86      0.83     11504
         1.0       0.85      0.78      0.82     11505

    accuracy                           0.82     23009
   macro avg       0.83      0.82      0.82     23009
weighted avg       0.83      0.82      0.82     23009



In [22]:
y_pred=XGBoost_grid.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.78      0.85      0.82      2877
         1.0       0.84      0.76      0.80      2876

    accuracy                           0.81      5753
   macro avg       0.81      0.81      0.81      5753
weighted avg       0.81      0.81      0.81      5753



<h3> Trying Random forests </h3>

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

In [23]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

<ipython-input-23-9e73616df194>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train,y_train)


In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.81      0.82      0.81      2877
         1.0       0.82      0.80      0.81      2876

    accuracy                           0.81      5753
   macro avg       0.81      0.81      0.81      5753
weighted avg       0.81      0.81      0.81      5753

